{
 "title": "Heizung",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Überblick", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "description": "[Admin](http://192.168.1.142:1880/ui/#!/1)\n## Vitoligno 300-P Viessmann\n- Kessel - Nennwärmeleistung  Pn 8 - 24 kW | Feuerungs-Nennwärmeleistung Qn 8,8 - 26.4 KW\n- Kesselklasse 3 | V 100l | PMS 3 bar | TN 95° | Seriennummer: 7452178101116109\n\n## Speicher Sonnenkraft PSR1000\n- **Heizwasser** Inhalt: 1000l | zul. Betriebstemperatur: 95 °C | zul. Betriebsüberdruck: 3 bar |\nSeriennummer: 8602 | Erstelldatum: 10/2011\n- **Solarregister**\nOberfläche: 3,0 m2 | zul. Betriebstemperatur: 110 °C | zul. Betriebsüberdruck: 10 bar",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"heating\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n//  |> range(start: -5m, stop:now())\n  |> filter(fn: (r) =>\n    (r._measurement == \"misc\") \n    and (   \n           r._field == \"heating.circuits.0.operating.modes.active\"\n        or r._field == \"heating.circuits.0.operating.programs.active\"\n    )\n  )\n  |> map(fn: (r) => ({r with \n      _value: if r._value == \"Heizung & Warmwasser\" then \"Heizung & WW\" else r._value\n    }))\n//  |> aggregateWindow(every: $__interval, fn: last)\n  |> last()\n  |> drop(columns: [\"_start\", \"_stop\", \"_time\"])\n  "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"heating\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  //|> range(start: -1d, stop:now())\n  |> filter(fn: (r) =>\n    r._measurement == \"temperature\" \n    and (r._field == \"heating.boiler.temperature\")\n  )\n  |> map(fn: (r) => ({r with \n        _value: if r._value > 0 then 1 else 0\n  }))\n  //|> stateDuration(fn: (r) => r._value > 0)\n  //|> filter(fn: (r) => r.stateDuration >= 0)\n  //|> difference(columns: [\"stateDuration\"], nonNegative: true)\n  //|> aggregateWindow(every: 1d, fn: sum, column: \"stateDuration\")\n  |> aggregateWindow(every: $__interval, fn: mean)\n  //|> tail(n: 10)\n  |> drop(columns: [\"_start\", \"_stop\"])\n\n"
    }
   ]
  },
  {
   "title": "Brennerstunden 10 Tage",
   "type": "stat",
   "description": "Heute und letzte 10 Tage",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"heating\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  //|> range(start: -1d, stop:now())\n  |> filter(fn: (r) =>\n    r._measurement == \"temperature\" \n    and (r._field == \"heating.boiler.temperature\")\n  )\n  |> stateDuration(fn: (r) => r._value > 0)\n//  |> filter(fn: (r) => r.stateDuration >= 0)\n  |> difference(columns: [\"stateDuration\"], nonNegative: true)\n  |> aggregateWindow(every: 1d, fn: sum, column: \"stateDuration\")\n  //|> aggregateWindow(every: $__interval, fn: mean)\n  |> tail(n: 10)\n  |> drop(columns: [\"_start\", \"_stop\"])\n\n"
    }
   ]
  },
  {
   "type": "barchart",
   "description": "Brennerstunden in den letzten 10 Tagen",
   "gridPos": { "h": 3, "w": 6, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "import \"experimental\"\nimport \"date\"\n\n// Define a helper function to return a formatted date\ndateString = (year=false, v) => {\n  d = string(v: date.monthDay(t: v))\n  m = string(v: date.month(t: v))\n  dm = d + \".\" + m + \".\"\n  //s = s + if s == true then \".\" + string(v: date.year(t: v)) else \"\"\n  y = if year then string(v: date.year(t: v)) else \"\"\n  s = dm + y\n  return s\n}\n\nfrom(bucket: \"heating\")\n  //|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> range(start: -10d, stop:now())\n  |> filter(fn: (r) =>\n    r._measurement == \"temperature\" \n    and (r._field == \"heating.boiler.temperature\")\n  )\n  |> stateDuration(fn: (r) => r._value > 0)\n  //|> filter(fn: (r) => r.stateDuration >= 0)\n  |> difference(columns: [\"stateDuration\"], nonNegative: true)\n  |> aggregateWindow(every: 1d, fn: sum, column: \"stateDuration\")\n  //|> aggregateWindow(every: $__interval, fn: mean)\n  |> tail(n: 10)\n  |> map(fn: (r) => ({r with \n      Datum: if date.hour(t: r._time) != 0 then \"Heute\" else dateString(v: experimental.addDuration(d: -1d, to: r._time))\n    }))\n  |> drop(columns: [\"_start\", \"_stop\"])\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"heating\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n//  |> range(start: -5m, stop:now())\n  |> filter(fn: (r) =>\n    r._measurement == \"temperature\" \n    and (r._field == \"heating.dhw.temperature.main\" or r._field == \"heating.circuits.0.targetTemperature\")\n  )\n  |> aggregateWindow(every: $__interval, fn: mean)\n  |> drop(columns: [\"_start\", \"_stop\", \"_time\"])\n  "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"heating\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n//  |> range(start: -10m, stop:now())\n  |> filter(fn: (r) =>\n    r._measurement == \"temperature\" \n    and (r._field == \"heating.dhw.sensors.temperature.hotWaterStorage\" or r._field == \"heating.boiler.sensors.temperature.main\")\n  )\n  |> aggregateWindow(every: $__interval, fn: mean)\n  |> drop(columns: [\"_start\", \"_stop\", \"_time\"])\n  "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"heating\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  //|> range(start: -5m, stop:now())\n  |> filter(fn: (r) =>\n    r._measurement == \"status\" \n    and (r._field == \"heating.dhw.pumps.circulation\" or r._field == \"heating.circuits.0.circulation.pump\" or r._field == \"heating.dhw.pumps.primary\")\n  )\n  |> aggregateWindow(every: $__interval, fn: mean)\n  |> drop(columns: [\"_start\", \"_stop\", \"_time\"])\n\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"heating\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  //|> range(start: today(), stop:now())\n  |> filter(fn: (r) =>\n    r._measurement == \"temperature\" \n    and (r._field == \"heating.sensors.temperature.outside\")\n  )\n//  |> aggregateWindow(every: 1d, fn: mean)\n  |> aggregateWindow(every: $__interval, fn: mean)\n  |> drop(columns: [\"_start\", \"_stop\"])\n\n"
    }
   ]
  },
  {
   "title": "⌀ Aussen 10 Tage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"heating\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  //|> range(start: today(), stop:now())\n  |> filter(fn: (r) =>\n    r._measurement == \"temperature\" \n    and (r._field == \"heating.sensors.temperature.outside\")\n  )\n//  |>last()\n  |> aggregateWindow(every: 1d, fn: mean)\n  //|> aggregateWindow(every: $__interval, fn: mean)\n  |> drop(columns: [\"_start\", \"_stop\"])\n\n"
    }
   ]
  },
  { "title": "Solarthermie", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Panel Ost",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"solar\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    (r._measurement == \"temperature\" and (r._field == \"Panel Ost\" )) //or r._field == \"Panel West\") )\n    or\n    (r._measurement == \"status\" and (r._field == \"Pumpe Ost\" )) // or r._field == \"Pumpe West\") )\n  )\n  |> aggregateWindow(every: $__interval, fn: mean)\n  |> drop(columns: [\"_start\", \"_stop\", \"_time\"])\n"
    }
   ]
  },
  {
   "title": "Panel West",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"solar\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    (r._measurement == \"temperature\" and (r._field == \"Panel West\" )) //or r._field == \"Panel West\") )\n    or\n    (r._measurement == \"status\" and (r._field == \"Pumpe West\" )) // or r._field == \"Pumpe West\") )\n  )\n  |> aggregateWindow(every: $__interval, fn: mean)\n  |> drop(columns: [\"_start\", \"_stop\", \"_time\"])\n"
    }
   ]
  },
  {
   "title": "Speicher",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"solar\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n//  |> range(start: -2h, stop:now())\n  |> filter(fn: (r) =>\n    r._measurement == \"temperature\"\n    and r._field == \"Pufferspeicher unten\"\n  )\n  |> aggregateWindow(every: $__interval, fn: mean)\n  |> drop(columns: [\"_start\", \"_stop\", \"_time\"])\n"
    }
   ]
  },
  {
   "title": "Fehler",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"solar\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n//  |> range(start: -2h, stop:now())\n  |> filter(fn: (r) =>\n    r._measurement == \"misc\" \n    and r._field == \"Fehler Maske\"\n  )\n  |> aggregateWindow(every: $__interval, fn: mean)\n  |> drop(columns: [\"_start\", \"_stop\", \"_time\"])\n"
    }
   ]
  },
  { "title": "Ascheschublade", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\nimport \"array\"\n\n// Define a helper function to return a formatted date\ndateString = (year=false, v) => {\n  d = string(v: date.monthDay(t: v))\n  m = string(v: date.month(t: v))\n  dm = d + \".\" + m + \".\"\n  //s = s + if s == true then \".\" + string(v: date.year(t: v)) else \"\"\n  y = if year then string(v: date.year(t: v)) else \"\"\n  s = dm + y\n  return s\n}\n\n\n// Define a helper function to get fields from the most recent pelletsfills entry\ngetLastPelletsfillsField = (value=\"_value\", field) => {\n    val = from(bucket: \"heating\")\n        |> range(start: -1y, stop: now())\n        |> filter(fn: (r) => r._measurement == \"pelletsfills\" and r._field == field)\n        |> last()\n        |> findColumn(fn: (key) => key._field == field, column: value)\n\n    return val[0]\n}\n\n// Define a helper function to get fields from the most recent pelletsfills entry\ngetLastAshtrayemptiesField = (value=\"_value\", field) => {\n    val = from(bucket: \"heating\")\n        |> range(start: -1y, stop: now())\n        |> filter(fn: (r) => r._measurement == \"ashtrayempty\" and r._field == field)\n        |> last()\n        |> findColumn(fn: (key) => key._field == field, column: value)\n\n    return val[0]\n}\n\ndateOfLastEmpty=getLastAshtrayemptiesField(field: \"percentfull\", value: \"_time\")\nx = from(bucket: \"heating\")\n  |> range(start: dateOfLastEmpty, stop: now())\n  |> filter(fn: (r) => r._measurement == \"misc\" and r._field == \"pellets.consumption\")\n  |> difference()\n  |> sum()\n  |> findColumn(fn: (key) => key._field == \"pellets.consumption\", column: \"_value\")\nconsumptionSinceLastEmpty = if exists x[0] then x[0] else 0.000001\n//extraconsumption=getLastAshtrayemptiesField(field: \"extraconsumption\")\npercentfull=getLastAshtrayemptiesField(field: \"percentfull\")\n\nnanoSecondsToDays=1000000000*60*60*24\ndurationSinceLastEmpty = duration(v: int(v: now()) - int(v: dateOfLastEmpty))\ndaysSinceLastEmpty = float(v: int(v: durationSinceLastEmpty)) / float(v: nanoSecondsToDays)\nconsumptionPerDay = consumptionSinceLastEmpty / daysSinceLastEmpty\n\nCAPACITY_PER_ASHTRAY=600.0 // Estimate of how many kg of pellets produce ash that fits into one tray load\nremainingCapacity = CAPACITY_PER_ASHTRAY - consumptionPerDay\n  \nrec = {\n    dateOfLastEmpty: dateOfLastEmpty,\n    dateOfLastEmptyDisplay: dateString(v: dateOfLastEmpty),\n    daysSinceLastEmpty : daysSinceLastEmpty,\n    consumptionSinceLastEmpty : consumptionSinceLastEmpty,\n    consumptionPerDay: consumptionPerDay,\n    percentFull :    consumptionSinceLastEmpty/CAPACITY_PER_ASHTRAY,   \n    daysRemainingTillFull:   remainingCapacity / consumptionPerDay,\n    weeksRemainingTillFull:  remainingCapacity / consumptionPerDay / 7.0,\n    monthsRemainingTillFull: remainingCapacity / consumptionPerDay / 30.0\n}\n\narray.from(rows: [rec])\n"
    }
   ]
  },
  { "title": "Pelletsverbrauch pro Tag", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "type": "barchart",
   "description": "Pellets Verbrauch pro Tag. Letzte 7 Tage",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "query": "import \"interpolate\"\nimport \"date\"\nimport \"strings\"\nimport \"experimental\"\n\n// Define a helper function to return a formatted date\ndateString = (year=false, v) => {\n  d = string(v: date.monthDay(t: v))\n  m = string(v: date.month(t: v))\n  dm = d + \".\" + m + \".\"\n  //s = s + if s == true then \".\" + string(v: date.year(t: v)) else \"\"\n  y = if year then string(v: date.year(t: v)) else \"\"\n  s = dm + y\n  return s\n}\n\n// Define a helper function to get fields from the most recent pelletsfills entry\ngetLastPelletsfillsField = (value=\"_value\", field) => {\n    val = from(bucket: \"heating\")\n        |> range(start: -1y, stop: now())\n        |> filter(fn: (r) => r._measurement == \"pelletsfills\" and r._field == field)\n        |> last()\n        |> findColumn(fn: (key) => key._field == field, column: value)\n\n    return val[0]\n}\n\nlastKg = getLastPelletsfillsField(field: \"kg\")\nlastPriceTotal = getLastPelletsfillsField(field: \"priceTotal\")\nlastPricePerKg = lastPriceTotal / lastKg\n\nbeginOfMeasurments=2022-03-24T00:00:00.00Z\nstarttime = -8d // need to add a day to get first day rigth\nstoptime = now()\nconsumption = from(bucket: \"heating\")\n  |> range(start: beginOfMeasurments, stop: stoptime)\n  |> filter(fn: (r) => r._measurement == \"misc\" and r._field == \"pellets.consumption\")\n  |> interpolate.linear(every: 1h)\n  |> difference()\n  |> range(start: starttime, stop:stoptime)\n  |> aggregateWindow(every: 1d, fn: sum)\n  |> map(fn: (r) => ({r with \n      Datum: if date.hour(t: r._time) != 0 then \"Heute\" else dateString(v: experimental.addDuration(d: -1d, to: r._time)),\n      Kosten: r._value * lastPricePerKg\n    }))\n  \ntemperature =  from(bucket: \"heating\")\n  |> range(start: beginOfMeasurments, stop: stoptime)\n  |> filter(fn: (r) => r._measurement == \"temperature\" and r._field == \"heating.sensors.temperature.outside\")\n  |> range(start: starttime, stop:stoptime)\n  |> aggregateWindow(every: 1d, fn: mean)\n\nsevenDaysAgo = experimental.addDuration(d: -7d, to: now())\njoin(tables: {t1: consumption, t2: temperature}, on: [\"_time\"])\n  |> map(fn: (r) => ({r with \n        Datum     : r.Datum,\n        Kosten    : if r.Kosten > 0.0 then r.Kosten else 0.0, //sometimes Kosten is undefined, return 0 then\n        consumption: if r._value_t1 > 0.0 then r._value_t1 else 0.0, //sometimes consumption is undefined, return 0 then\n        temperature: r._value_t2\n    }))\n    |> filter(fn: (r) => r._time > sevenDaysAgo)\n    |> keep(columns: [\"Kosten\", \"Datum\", \"consumption\", \"temperature\", \"_time\"])\n    |> yield(name: \"consumption and temperature\")\n"
    }
   ]
  },
  {
   "title": "Durchschnitt letzte 7 Tage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"interpolate\"\nimport \"date\"\nimport \"strings\"\nimport \"experimental\"\n// Define a helper function to get fields from the most recent pelletsfills entry\ngetLastPelletsfillsField = (value=\"_value\", field) => {\n    val = from(bucket: \"heating\")\n        |> range(start: -1y, stop: now())\n        |> filter(fn: (r) => r._measurement == \"pelletsfills\" and r._field == field)\n        |> last()\n        |> findColumn(fn: (key) => key._field == field, column: value)\n\n    return val[0]\n}\n\nlastKg = getLastPelletsfillsField(field: \"kg\")\nlastPriceTotal = getLastPelletsfillsField(field: \"priceTotal\")\nlastPricePerKg = lastPriceTotal / lastKg\n\nbeginOfMeasurments=2022-03-24T00:00:00.00Z\nstarttime = -8d // need to add a day to get first day rigth\nsevenDaysAgo = experimental.addDuration(d: -7d, to: now())\nstoptime = now()\nfrom(bucket: \"heating\")\n  |> range(start: beginOfMeasurments, stop: stoptime)\n  |> filter(fn: (r) => r._measurement == \"misc\" and r._field == \"pellets.consumption\")\n  |> interpolate.linear(every: 1h)\n  |> difference()\n  |> range(start: starttime, stop:stoptime)\n  |> aggregateWindow(every: 1d, fn: sum)\n  |> filter(fn: (r) => r._time > sevenDaysAgo)\n  // sometimes we get the last days with 0 consumption - not clear how that happens.\n  //|> filter(fn: (r) => r._value > 0)\n  // filter out the last, ongoing day windows because it would distort the average\n  |> filter(fn: (r) => date.hour(t: r._time) == 0)\n  |> map(fn: (r) => ({ r with _value: if r._value > 0.0 then r._value else 0.0 })) // when the value is undefined it should count as 0\n  |> mean()\n  |> map(fn: (r) => ({r with \n        price: lastPricePerKg * r._value\n    }))\n  |> drop(columns: [\"_start\", \"_stop\"])\n  "
    }
   ]
  },
  { "title": "Pelletsverbrauch pro Woche", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "type": "barchart",
   "description": "Letzte 8 Wochen.\nAus technischen Gründen beginnt eine neue Woche immer Donnerstags um Mitternacht",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "query": "import \"interpolate\"\nimport \"math\"\nimport \"date\"\nimport \"strings\"\nimport \"experimental\"\n\n// Define a helper function to return a formatted date\ndateString = (year=false, v) => {\n  d = string(v: date.monthDay(t: v))\n  m = string(v: date.month(t: v))\n  dm = d + \".\" + m + \".\"\n  //s = s + if s == true then \".\" + string(v: date.year(t: v)) else \"\"\n  y = if year then string(v: date.year(t: v)) else \"\"\n  s = dm + y\n  return s\n}\n\n// Define a helper function to get fields from the most recent pelletsfills entry\ngetLastPelletsfillsField = (value=\"_value\", field) => {\n    val = from(bucket: \"heating\")\n        |> range(start: -1y, stop: now())\n        |> filter(fn: (r) => r._measurement == \"pelletsfills\" and r._field == field)\n        |> last()\n        |> findColumn(fn: (key) => key._field == field, column: value)\n\n    return val[0]\n}\n\nlastKg = getLastPelletsfillsField(field: \"kg\")\nlastPriceTotal = getLastPelletsfillsField(field: \"priceTotal\")\nlastPricePerKg = lastPriceTotal / lastKg\n\nstoptime = now()\ntemperature =  from(bucket: \"heating\")\n  |> range(start: 2022-03-24T00:00:00.00Z, stop: stoptime)\n  |> filter(fn: (r) =>\n    r._measurement == \"temperature\" and\n    r._field == \"heating.sensors.temperature.outside\"\n  )\n  |> range(start: -8w, stop:stoptime)\n  |> aggregateWindow(every: 1w, fn: mean)\n  |> drop(columns: [\"_start\", \"_stop\"])\n  // in the future this wont be needed but right now we end up with an \"empty\" week at the beginning\n//  |> filter(fn: (r) => r._value > 0)\n  \nconsumption = from(bucket: \"heating\")\n  |> range(start: 2022-03-24T00:00:00.00Z, stop: stoptime)\n  |> filter(fn: (r) =>\n    r._measurement == \"misc\" and\n    r._field == \"pellets.consumption\"\n  )\n  |> interpolate.linear(every: 1h)\n  |> range(start: -8w, stop:stoptime)\n  |> difference()\n  |> aggregateWindow(every: 1w, fn: sum)\n  |> map(fn: (r) => ({r with \n      _value: math.roundtoeven(x: r._value),\n      Datum: if date.hour(t: r._time) != 0 then \"Seit Donnerstag\" else dateString(v: experimental.addDuration(d: -1d, to: r._time)),\n      Kosten : r._value * lastPricePerKg\n    }))\n  |> drop(columns: [\"_start\", \"_stop\"])\n  // in the future this wont be needed but right now we end up with an \"empty\" week at the beginning\n  //|> filter(fn: (r) => r._value > 0)\n  \n  join(tables: {t1: consumption, t2: temperature}, on: [\"_time\"])\n    |> map(fn: (r) => ({r with \n        Datum     : r.Datum,\n        Kosten    : if r.Kosten > 0.0 then r.Kosten else 0.0, //sometimes Kosten is undefined, return 0 then\n        consumption: if r._value_t1 > 0.0 then r._value_t1 else 0.0, //sometimes consumption is undefined, return 0 then\n        temperature: r._value_t2\n    }))\n//    |> filter(fn: (r) => r.consumption > 0)\n    |> keep(columns: [\"Datum\", \"consumption\", \"temperature\", \"Kosten\", \"_time\"])\n    |> yield(name: \"consumption and temperature\")\n"
    }
   ]
  },
  {
   "title": "Wochendurchschnitt letzte 8 Wochen",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 18, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\nimport \"interpolate\"\n\n// Define a helper function to get fields from the most recent pelletsfills entry\ngetLastPelletsfillsField = (value=\"_value\", field) => {\n    val = from(bucket: \"heating\")\n        |> range(start: -1y, stop: now())\n        |> filter(fn: (r) => r._measurement == \"pelletsfills\" and r._field == field)\n        |> last()\n        |> findColumn(fn: (key) => key._field == field, column: value)\n\n    return val[0]\n}\n\nlastKg = getLastPelletsfillsField(field: \"kg\")\nlastPriceTotal = getLastPelletsfillsField(field: \"priceTotal\")\nlastPricePerKg = lastPriceTotal / lastKg\n\nfrom(bucket: \"heating\")\n  |> range(start: 2022-03-24T00:00:00.00Z, stop: now())\n  |> filter(fn: (r) => r._measurement == \"misc\" and r._field == \"pellets.consumption\")\n  |> interpolate.linear(every: 1h)\n  |> range(start: -8w, stop: now())\n  |> difference()\n  |> aggregateWindow(every: 1w, fn: sum)\n  |> filter(fn: (r) => date.hour(t: r._time) == 0)\n  //|> map(fn: (r) => ({ r with _value: if r._value > 0.0 then r._value else 0.0 })) // when the value is undefined it should count as 0\n  |> mean()\n  |> map(fn: (r) => ({r with \n      price: lastPricePerKg * r._value\n  }))\n  |> drop(columns: [\"_start\", \"_stop\", \"_field\", \"_measurement\"])"
    }
   ]
  },
  {
   "title": "Pelletsverbrauch pro Monat & Gesamt",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 }
  },
  {
   "type": "barchart",
   "description": "Verbrauch pro Monat. Letzte 12 Monate",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "query": "import \"interpolate\"\nimport \"date\"\nimport \"strings\"\nimport \"experimental\"\n\n// Define a helper function to return a formatted date\ndateString = (year=false, day=true, v) => {\n  d = string(v: date.monthDay(t: v))\n  m = string(v: date.month(t: v))\n  dm = if day then d + \".\" + m + \".\" else  m + \".\"\n  //s = s + if s == true then \".\" + string(v: date.year(t: v)) else \"\"\n  y = if year then string(v: date.year(t: v)) else \"\"\n  s = dm + y\n  return s\n}\n\n// Define a helper function to get fields from the most recent pelletsfills entry\ngetLastPelletsfillsField = (value=\"_value\", field) => {\n    val = from(bucket: \"heating\")\n        |> range(start: -1y, stop: now())\n        |> filter(fn: (r) => r._measurement == \"pelletsfills\" and r._field == field)\n        |> last()\n        |> findColumn(fn: (key) => key._field == field, column: value)\n\n    return val[0]\n}\n\nlastKg = getLastPelletsfillsField(field: \"kg\")\nlastPriceTotal = getLastPelletsfillsField(field: \"priceTotal\")\nlastPricePerKg = lastPriceTotal / lastKg\n\n//beginOfMeasurments=2022-03-24T00:00:00.00Z\nbeginOfMeasurments=2022-04-01T00:00:00.00Z // start at beginning of the first month where we have complete measurements\nstoptime = now()\n\ntemperature =  from(bucket: \"heating\")\n  |> range(start: beginOfMeasurments, stop: stoptime)\n  |> filter(fn: (r) => r._measurement == \"temperature\" and r._field == \"heating.sensors.temperature.outside\")\n  |> range(start: -12mo, stop:stoptime)\n  |> aggregateWindow(every: 1mo, fn: mean)\n  |> drop(columns: [\"_start\", \"_stop\"])\n  // in the future this wont be needed but right now we end up with an \"empty\" week at the beginning\n  |> filter(fn: (r) => r._value > 0)\n\nconsumption = from(bucket: \"heating\")\n  |> range(start: beginOfMeasurments, stop: stoptime)\n  |> filter(fn: (r) => r._measurement == \"misc\" and r._field == \"pellets.consumption\")\n  |> interpolate.linear(every: 1h)\n  |> difference()\n  |> range(start: -12mo, stop:stoptime)\n  |> aggregateWindow(every: 1mo, fn: sum)\n  |> map(fn: (r) => ({r with \n      Datum: if date.hour(t: r._time) != 0 then \"Laufender Monat\" else dateString(v: experimental.addDuration(d: -1mo, to: r._time), year: true, day: false),\n      Kosten : r._value * lastPricePerKg\n    }))\n  |> drop(columns: [\"_start\", \"_stop\"])\n  |> filter(fn: (r) => r._value > 0)\n  |> sort(desc: true, columns: [\"Datum\"])\n\n  join(tables: {t1: consumption, t2: temperature}, on: [\"_time\"])\n    |> map(fn: (r) => ({r with \n        Datum     : r.Datum,\n        Kosten    : if r.Kosten > 0.0 then r.Kosten else 0.0, //sometimes Kosten is undefined, return 0 then\n        consumption: if r._value_t1 > 0.0 then r._value_t1 else 0.0, //sometimes consumption is undefined, return 0 then\n        temperature: r._value_t2\n    }))\n    |> filter(fn: (r) => r.consumption > 0)\n    |> keep(columns: [\"Datum\", \"consumption\", \"temperature\", \"Kosten\", \"_time\"])\n    |> yield(name: \"consumption and temperature\")\n"
    }
   ]
  },
  {
   "title": "Monatsdurchschnitt letzte 12 Monate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 18, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"interpolate\"\nimport \"date\"\nimport \"math\"\nimport \"experimental\"\n\n// Define a helper function to get the minimum of two durations\nmaxTime = (x , y) => {\n  xFloat = float(v: int(v: x))\n  yFloat = float(v: int(v: y))\n  maxFloat = math.mMax(x: xFloat, y: yFloat)\n  return time(v: int(v: maxFloat))\n}\n// Define a helper function to get the minimum of two durations\nminTime = (x , y) => {\n  xFloat = float(v: int(v: x))\n  yFloat = float(v: int(v: y))\n  minFloat = math.mMin(x: xFloat, y: yFloat)\n  return time(v: int(v: minFloat))\n}\n\n// Define a helper function to get fields from the most recent pelletsfills entry\ngetLastPelletsfillsField = (value=\"_value\", field) => {\n    val = from(bucket: \"heating\")\n        |> range(start: -1y, stop: now())\n        |> filter(fn: (r) => r._measurement == \"pelletsfills\" and r._field == field)\n        |> last()\n        |> findColumn(fn: (key) => key._field == field, column: value)\n\n    return val[0]\n}\n\nlastKg = getLastPelletsfillsField(field: \"kg\")\nlastPriceTotal = getLastPelletsfillsField(field: \"priceTotal\")\nlastPricePerKg = lastPriceTotal / lastKg\n\nbeginOfMeasurments=2022-04-01T00:00:00.00Z // start at beginning of the first month where we have complete measurements\nbeginOfAggregation = maxTime(x: experimental.subDuration(d: 12mo, from: now()), y: beginOfMeasurments) // not really necessary as there are no values before being of measurements anyway\nstoptime = now()\n\nfrom(bucket: \"heating\")\n  |> range(start: beginOfMeasurments, stop: stoptime)\n  |> filter(fn: (r) => r._measurement == \"misc\" and r._field == \"pellets.consumption\")\n  |> interpolate.linear(every: 1h)\n  |> difference()\n  |> range(start: beginOfAggregation, stop:stoptime)\n  |> aggregateWindow(every: 1mo, fn: sum)\n  |> filter(fn: (r) => r._value > 0)\n  // filter out the last, ongoing day windows because it would distort the average\n  |> filter(fn: (r) => date.hour(t: r._time) == 0)\n  |> map(fn: (r) => ({ r with _value: if r._value > 0.0 then r._value else 0.0 })) // when the value is undefined it should count as 0\n  |> mean()\n  |> map(fn: (r) => ({r with \n      price: lastPricePerKg * r._value,\n      beginOfAggregation: time(v: beginOfAggregation)\n    }))\n  |> drop(columns: [\"_start\", \"_stop\"])\n    \n"
    }
   ]
  },
  {
   "title": "Pelletsverbrauch: Gesamt & seit 04 2022",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 18, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "kg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"interpolate\"\nimport \"math\"\nfrom(bucket: \"heating\")\n  |> range(start: 2022-03-24T00:00:00.00Z, stop:now())\n  |> filter(fn: (r) =>\n    r._measurement == \"misc\" and\n    r._field == \"pellets.consumption\"\n  )\n  |> last()"
    },
    {
     "query": "import \"interpolate\"\nimport \"math\"\nfrom(bucket: \"heating\")\n  |> range(start: 2022-03-24T00:00:00.00Z, stop:now())\n  |> filter(fn: (r) =>\n    r._measurement == \"misc\" and\n    r._field == \"pellets.consumption\"\n  )\n  |> difference()\n  |> sum()\n  |> map(fn: (r) => ({r with \n      _value: math.roundtoeven(x: r._value)\n    }))\n  |> last()"
    }
   ]
  },
  {
   "title": "Pellets Verbrauchsprognose",
   "type": "stat",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "query": "import \"date\"\nimport \"array\"\n\n// Define a helper function to get fields from the most recent pelletsfills entry\ngetLastPelletsfillsField = (value=\"_value\", field) => {\n    val = from(bucket: \"heating\")\n        |> range(start: -1y, stop: now())\n        |> filter(fn: (r) => r._measurement == \"pelletsfills\" and r._field == field)\n        |> last()\n        |> findColumn(fn: (key) => key._field == field, column: value)\n\n    return val[0]\n}\n\ndateOfLastRefill=getLastPelletsfillsField(field: \"kg\", value: \"_time\")\nx = from(bucket: \"heating\")\n  |> range(start: dateOfLastRefill, stop: now())\n  |> filter(fn: (r) => r._measurement == \"misc\" and r._field == \"pellets.consumption\")\n  |> difference()\n  |> sum()\n  |> findColumn(fn: (key) => key._field == \"pellets.consumption\", column: \"_value\")\nconsumptionSinceRefill = x[0]\n\nnanoSecondsToDays=1000000000*60*60*24\ndurationSinceLastRefill = duration(v: int(v: now()) - int(v: dateOfLastRefill))\ndaysSinceLastRefill = float(v: int(v: durationSinceLastRefill)) / float(v: nanoSecondsToDays)\npelletsAfterLastRefill=getLastPelletsfillsField(field: \"kg\")\nremainingPellets = pelletsAfterLastRefill-consumptionSinceRefill\nconsumptionPerDay = consumptionSinceRefill / daysSinceLastRefill\n  \nrec = {\n    consumptionSinceRefill: consumptionSinceRefill / 1000.0, \n    pelletsAfterLastRefill: pelletsAfterLastRefill / 1000.0,\n    remainingPellets: remainingPellets / 1000.0,\n    daysSinceLastRefill: daysSinceLastRefill,\n    consumptionPerDay: consumptionPerDay,\n    daysRemainingTillEmpty:   remainingPellets / consumptionPerDay,\n    weeksRemainingTillEmpty:  remainingPellets / consumptionPerDay / 7.0,\n    monthsRemainingTillEmpty: remainingPellets / consumptionPerDay / 30.0\n}\n\narray.from(rows: [rec])\n"
    }
   ]
  },
  { "title": "Temperaturen und Zeitverläufe", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Temperaturverläufe",
   "type": "timeseries",
   "description": "- Rot: Heizung\n- Blau: Warmwasser/Pufferspeicher\n- Lila: Solarthermie\n- Grün: Aussentemperatur\n- Gestrichelt: Soll-Temperaturen",
   "gridPos": { "h": 23, "w": 23, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"heating\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"temperature\" \n  )\n  |> aggregateWindow(every: $__interval, fn: mean)\n"
    },
    {
     "query": "from(bucket: \"solar\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"temperature\"\n    and r._field != \"S4\"\n  )\n  |> aggregateWindow(every: $__interval, fn: mean)\n"
    }
   ]
  },
  {
   "title": "Solarthermie Pumpenleistung",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"solar\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"status\" \n  )\n  |> aggregateWindow(every: $__interval, fn: mean)\n"
    }
   ]
  },
  {
   "title": "Brennerstarts",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 23, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "query": "from(bucket: \"heating\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"status\" and\n    r._field == \"burner.started\"\n  )"
    }
   ]
  },
  {
   "title": "Warmwasser Zirkulationspumpe",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 23, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "query": "from(bucket: \"heating\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"status\" and\n    r._field == \"heating.dhw.pumps.circulation\"\n  )"
    }
   ]
  },
  {
   "title": "Warmwasser Speicherladepumpe",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 23, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "query": "from(bucket: \"heating\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"status\" and\n    r._field == \"heating.dhw.pumps.primary\"\n  )"
    }
   ]
  },
  {
   "title": "Heizkreis Umwälzpumpe",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 23, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "query": "from(bucket: \"heating\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"status\" and\n    r._field == \"heating.circuits.0.circulation.pump\"\n  )"
    }
   ]
  },
  {
   "title": "Betriebsprogramm",
   "type": "timeseries",
   "description": "0:Normal 1:Reduziert 2:Manuell 3:Standby 4:Extern 5:Komfort 6:Eco 7:Fixed 8:Urlaub 9:Urlaub zu Hause 10:forcedLastFromSchedule",
   "gridPos": { "h": 4, "w": 23, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"heating\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"status\" and\n    r._field == \"heating.circuits.0.operating.programs.active.num\"\n  )"
    }
   ]
  },
  {
   "title": "Betriebsmodus",
   "type": "timeseries",
   "description": "0:Heizung & Warmwasser  1:Nur Heizung  2:Nur Warmwasser  3:Manuell Reduziert  4:Manuell Normal",
   "gridPos": { "h": 4, "w": 23, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"heating\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"status\" and\n    r._field == \"heating.circuits.0.operating.modes.active.num\"\n  )"
    }
   ]
  },
  {
   "title": "Warmwasser Aktiv",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 23, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "query": "from(bucket: \"heating\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"status\" and\n    r._field == \"heating.dhw.charging\"\n  )"
    }
   ]
  },
  {
   "title": "Warmwasser Status",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 23, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "query": "from(bucket: \"heating\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"status\" and\n    r._field == \"heating.dhw\"\n  )"
    }
   ]
  },
  {
   "title": "Frostschutz",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 23, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "query": "from(bucket: \"heating\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"status\" and\n    r._field == \"heating.circuits.0.frostprotection\"\n  )"
    }
   ]
  },
  {
   "title": "Tagesverbrauch Pellets",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 23, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "query": "import \"interpolate\"\nfrom(bucket: \"heating\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"misc\" and\n    r._field == \"pellets.consumption\"\n  )\n  |> interpolate.linear(every: 1d)\n  |> difference()\n  |> aggregateWindow(every: 1d, fn: sum)\n"
    }
   ]
  },
  { "title": "Sonstige Informationen", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 } },
  {
   "title": "Pellets Füllungen & historische Verbrauchswerte",
   "type": "table",
   "description": "kg/Jahr ist hochgerechnet aus kg/Tag*365\n\nAllgemein geht man bei einer Wohnfläche von 250 m² von folgendem Holzpellets Verbrauch aus:\n* Altbauten bis 1977 verbrauchen 40kg/m²a Pellets. Im Jahr also 10.000 kg\n* Bauten bis 2003 verbrauchen 20 kg/m²a Pellets. Im Jahr also nur 5.000 kg\n* Ein KfW Effizienzhaus verbraucht 12 kg/m²a Pellets. Im Jahr also nur noch 3.000 kg\n* Ein Passivhaus hat einen Pelletverbrauch von 3 kg/m²a Pellets. Im Jahr also nur 750 kg",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 107 },
   "targets": [
    {
     "query": "import \"contrib/tomhollingworth/events\"\n// Define a helper function to extract field values\ngetFieldValue = (tables=<-, value=\"_value\", field) => {\n    extract = tables\n        |> findColumn(fn: (key) => key._field == field, column: value)\n\n    return extract[0]\n}\n\nstarttime = -5y\nlastFillTime =\n    from(bucket: \"heating\")\n        |> range(start: starttime, stop: now())\n        |> filter(fn: (r) => r._measurement == \"pelletsfills\" and r._field == \"kg\")\n        |> last()\n        |> getFieldValue(value: \"_time\", field: \"kg\")\n\nconsumedPelletsSinceLastFill = from(bucket: \"heating\")\n  |> range(start: lastFillTime, stop: now())\n  |> filter(fn: (r) => r._measurement == \"misc\" and r._field == \"pellets.consumption\" )\n  |> difference()\n  |> sum()\n  |> getFieldValue(field: \"pellets.consumption\")\n\nkg =\n    from(bucket: \"heating\")\n        |> range(start: starttime, stop: now())\n        |> filter(fn: (r) => r._measurement == \"pelletsfills\" and r._field == \"kg\")\n\nrestKg =\n    from(bucket: \"heating\")\n        |> range(start: starttime, stop: now())\n        |> filter(fn: (r) => r._measurement == \"pelletsfills\" and r._field == \"restKg\")\n\npriceTotal =\n    from(bucket: \"heating\")\n        |> range(start: starttime, stop: now())\n        |> filter(fn: (r) => r._measurement == \"pelletsfills\" and r._field == \"priceTotal\")\n\nj1 = join(tables: {t1: kg, t2: priceTotal}, on: [\"_time\"])\n    |> map(fn: (r) => ({r with \n        kg: r._value_t1, \n        priceTotal: r._value_t2,\n        priceKg: r._value_t2 / r._value_t1\n    }))\n  |> keep(columns: [\"kg\", \"priceTotal\", \"priceKg\", \"_time\"])\n\njoin(tables: {t1: j1, t2: restKg}, on: [\"_time\"])\n    |> map(fn: (r) => ({r with \n        restKg: if (r._time == lastFillTime) then r.kg-consumedPelletsSinceLastFill else r._value\n    }))\n    |> events.duration(unit: 1d, columnName: \"days\")\n    |> events.duration(unit: 1mo, columnName: \"months\")\n    |> map(fn: (r) => ({r with \n        kgPerDay: (r.kg-r.restKg) / float(v: r.days),\n        kgPerMonth: if (r.months == 0.0) then 0.0 else (r.kg-r.restKg) / float(v: r.months),\n        kgPerYear: ((r.kg-r.restKg) / float(v: r.days)) * 365.0,\n        consumedPelletsSinceLastFill: consumedPelletsSinceLastFill\n    }))\n    |> keep(columns: [\"kg\", \"priceTotal\", \"priceKg\", \"restKg\", \"days\", \"months\", \"kgPerDay\", \"kgPerMonth\", \"kgPerYear\", \"_time\"])\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "Stunden" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"experimental\"\n\nstarttime = experimental.addDuration(d: -5m, to: now())\nhours =\n    from(bucket: \"heating\")\n        |> range(start: starttime, stop: now())\n        |> filter(fn: (r) => r._measurement == \"misc\" and r._field == \"heating.burners.0.statistics.hours\")\n        |> drop(columns: [\"_start\", \"_stop\"])\n        |> last()\n\nstarts =\n    from(bucket: \"heating\")\n        |> range(start: starttime, stop: now())\n        |> filter(fn: (r) => r._measurement == \"misc\" and r._field == \"heating.burners.0.statistics.starts\")\n        |> drop(columns: [\"_start\", \"_stop\"])\n        |> last()\n\njoin(tables: {t1: starts, t2: hours}, on: [\"_time\"])\n    |> map(fn: (r) => ({r with \n        starts: r._value_t1, \n        hours: r._value_t2,\n        hoursPerStart: r._value_t2 / r._value_t1\n    }))\n    |> keep(columns: [\"starts\", \"hours\", \"hoursPerStart\"])\n    \n"
    }
   ]
  },
  {
   "title": "Solarthermie Betriebstunden",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"solar\")\n  |> range(start: -1h, stop:now())\n  |> filter(fn: (r) =>\n    r._measurement == \"misc\" \n    and r._field =~ /Betriebsstunden.*/\n  )\n  |> last()"
    }
   ]
  },
  {
   "title": "Ascheschublade Leerungen",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "Tage" } },
   "targets": [
    {
     "query": "import \"date\"\nimport \"contrib/tomhollingworth/events\"\n\n// Define a helper function to return a formatted date\ndateString = (year=false, v) => {\n  d = string(v: date.monthDay(t: v))\n  m = string(v: date.month(t: v))\n  dm = d + \".\" + m + \".\"\n  //s = s + if s == true then \".\" + string(v: date.year(t: v)) else \"\"\n  y = if year then string(v: date.year(t: v)) else \"\"\n  s = dm + y\n  return s\n}\n\nfrom(bucket: \"heating\")\n  |> range(start: -2y, stop:now())\n  |> filter(fn: (r) =>\n    r._measurement == \"ashtrayempty\" \n    //and r._field == \"example-field\"\n  )\n  |> events.duration(unit: 1d, columnName: \"days\")\n  |> map(fn: (r) => ({r with \n        Datum: dateString(v: r._time, year: true)\n    }))\n  |> drop(columns: [\"_start\", \"_stop\"])\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 127 },
   "options": {
    "content": "## Heizung Zum Lauchwald 15\n[Admin](http://192.168.1.142:1880/ui/#!/1)\n## Vitoligno 300-P Viessmann\n- Kessel - Nennwärmeleistung  Pn 8 - 24 kW | Feuerungs-Nennwärmeleistung Qn 8,8 - 26.4 KW\n- Kesselklasse 3 | V 100l | PMS 3 bar | TN 95° | Seriennummer: 7452178101116109\n\n## Speicher Sonnenkraft PSR1000\n- **Heizwasser** Inhalt: 1000l | zul. Betriebstemperatur: 95 °C | zul. Betriebsüberdruck: 3 bar |\nSeriennummer: 8602 | Erstelldatum: 10/2011\n- **Solarregister**\nOberfläche: 3,0 m2 | zul. Betriebstemperatur: 110 °C | zul. Betriebsüberdruck: 10 bar"
   }
  },
  {
   "title": " ",
   "type": "text",
   "gridPos": { "h": 2, "w": 11, "x": 0, "y": 139 },
   "options": {
    "content": "[Admin](http://192.168.1.142:1880/ui/#!/1)"
   }
  }
 ]
}